### ISSUE TITLE
Polylinestring that contains the sequence  "\N" triggers error in unicodeescape 

### ISSUE THREAD

**Issue by jjvanhoutte** [ismailsunni/qgis-encoded-polyline#2]
I was able to adapt the code to apply it to a table of polylines, but encountered following error, also when applying that string directly to the qgis-encoded-polyline plugin:

String to convert: ulcxHwzgYp@yBJs@@YAk@Ik@cAgE}CmMu@eDM}@kHsWOi@Gi@A}@Nq@P[NO^IN@THTRRn@Px@b@vBpDjRpBvJp@xC^tAx@xCdAjD\v@|@x@`A\`A`@PRRJ\NLPFNBXA^Wr@

[problematicPolylinestring1.txt](https://github.com/ismailsunni/qgis-encoded-polyline/files/9972139/problematicPolylinestring1.txt)

Error:
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 118-119: malformed \N character escape 
Traceback (most recent call last):
  File "D:\Users/jeroen.vanhoutte/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\encoded-polyline\main_dialog.py", line 76, in load_polyline
    polyline_string = codecs.decode(polyline_string, "unicode_escape")
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 118-119: malformed \N character escape

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.12-Białowieża Białowieża, b8534cb1

**Comment by jjvanhoutte** [comment]
Other strings give string index out of range:

String:
w~uwHukqX|ACnBQjb@m@fLYnAS~@Qn@_@`BkAjD_DtE_G`Aq@LCJCtCa@zIs@pBU|Cy@rAkAz@y@rAaA|AeAx@c@tA]~@EfAFvAR|ALnD^tBXVBpHt@~A^jCtAzAfArErD~A|@rAf@bL`DzGdB`Ct@^P`@\r@t@vHxJtJ`MtO~R`FxGtGhLxB|DrA|BtAhB`@n@Xj@L`@Dl@NxJJtIF|APXh@l@fBHp@Vj@\\ZXf@Z|@^z@nA|D|AjDtGfMrClGx@~AlKhMrB{AbF{CvAfIFXPTLHzALn@@jFJLBPRNt@HRPRRJ`@Lr@LhCLFKJIjGmBr@WvDsAxAa@dAW~@O`Em@tDe@~@e@ZWlImGrGdYrAdG{A~BkBvCiIjM]n@[x@Uz@Sz@M~@MjAE~AAbABfAJnA`AtFg@JW?

[problematicPolylinestring2.txt](https://github.com/ismailsunni/qgis-encoded-polyline/files/9972140/problematicPolylinestring2.txt)

Error:
IndexError: string index out of range 
Traceback (most recent call last):
  File "D:\Users/jeroen.vanhoutte/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\encoded-polyline\main_dialog.py", line 77, in load_polyline
    coordinates = polyline_decode(
  File "D:\Users/jeroen.vanhoutte/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\encoded-polyline\polyline.py", line 88, in decode
    return PolylineCodec().decode(expression, precision, geojson)
  File "D:\Users/jeroen.vanhoutte/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\encoded-polyline\polyline.py", line 53, in decode
    lng_change, index = self._trans(expression, index)
  File "D:\Users/jeroen.vanhoutte/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\encoded-polyline\polyline.py", line 33, in _trans
    byte = ord(value[index]) - 63
IndexError: string index out of range


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.12-Białowieża Białowieża, b8534cb1

**Comment by jjvanhoutte** [comment]
Looks like the strings did not survive the int
[problematicPolylinestring1.txt](https://github.com/ismailsunni/qgis-encoded-polyline/files/9972139/probl
[problematicPolylinestring2.txt](https://github.com/ismailsunni/qgis-encoded-polyline/files/9972140/problematicPolylinestring2.txt)
ematicPolylinestring1.txt)
erpretation of the formatter. I add them as text files.

**Comment by jjvanhoutte** [comment]
I tried replacing "unicode_escape"  with "raw"  but then the following string gave an error: 
[problematicPolylinestring3.txt](https://github.com/ismailsunni/qgis-encoded-polyline/files/9972634/problematicPolylinestring3.txt)

TypeError: decoding with 'unicode_escape' codec failed (TypeError: a bytes-like object is required, not 'QVariant')

**Comment by ismailsunni** [comment]
Hi @jjvanhoutte 
Thansk for your bug report. I have check for all those 3 samples that you give to me:

1. It works fine
    ![image](https://user-images.githubusercontent.com/1421861/200979486-7ea93e3b-de5f-4dcb-b51a-715f554b3626.png)

2. It seems the same issue as in https://github.com/frederickjansen/polyline/issues/4 (the library behind the plugin Try to add `@` as mentioned it the issue, it will be a valid polyline.
![image](https://user-images.githubusercontent.com/1421861/200980791-c826e39f-5003-453e-afdf-4dc7562ff390.png)

3. It works fine 
    ![image](https://user-images.githubusercontent.com/1421861/200979587-79317841-fc2d-4936-b965-89ff7635575b.png)

Does the error only occur when you apply it to a table of polylines? And how do you do it?

**Comment by jjvanhoutte** [comment]
Thank you.
Adding the @ helped.

In my own code I can solve it also by removing the codecs.decode statement: 
`polyline_string = codecs.decode(polyline_string, "unicode_escape")`
I assume reading from a layer I don't need that - as opposed to when working with plain text from user input. 

I uploaded the code in a separate project: https://github.com/jjvanhoutte/qgis_encoded_polyline_table

**Comment by ismailsunni** [comment]
Thanks @jjvanhoutte 
I quickly check your repository, actually, you only need to install the `polyline` library in your system and all should work. See: https://github.com/frederickjansen/polyline#installation

Anyway, thanks for using my plugin :+1:
